spring.application.name=Bank-System-App

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=ORACLEBANKSYSTEMMANAGMENT
spring.datasource.password=root00

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

